dependencies {
    implementation(project(":core:model"))
    implementation(project(":core:domain"))
    implementation(project(":core:data"))
    implementation(project(":core:ui"))
    implementation(project(":feature:login"))
    implementation(project(":feature:task"))
    implementation(project(":feature:env"))
    implementation(project(":feature:script"))
    implementation(project(":feature:dependency"))
    implementation(project(":feature:log"))
    implementation(project(":feature:settings"))